// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics_Shop.DBModels;

public partial class Account
{
    public int Id { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Role { get; set; }

    public string Token { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}