// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics_Shop.DBModels;

public partial class OrderItem
{
    

    public int Id { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public int Quantity { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public OrderItem()
    {
        Id = 0;
        OrderId = 0;
        ProductId = 0;
        Quantity = 0;
        Order = null;
        Product = null;
    }

    public OrderItem(int id, int orderId, int productId, int quantity, Order order, Product product)
    {
        Id = id;
        OrderId = orderId;
        ProductId = productId;
        Quantity = quantity;
        Order = order;
        Product = product;
    }

   
}