// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics_Shop.DBModels;

public partial class Order
{         
    public int Id { get; set; }

    public int UserId { get; set; }

    public int OrderStatus { get; set; }

    public DateTime OrderDate { get; set; }

    public int PaymentMethod { get; set; }

    public int ShippingMethod { get; set; }

    public int? VoucherId { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual User User { get; set; }

    public virtual Voucher Voucher { get; set; }

    public Order()
    {
        Id = 0;
        UserId = 0;
        OrderStatus = 0;
        OrderDate = DateTime.Now;
        PaymentMethod = 0;
        ShippingMethod = 0;
        VoucherId = 0;
        User = null;
        Voucher = null;

    }

    public Order(int id, int userId, int orderStatus, DateTime orderDate, int paymentMethod, int shippingmethod,  int? voucherId, User user, Voucher voucher )
    {
        Id = id;
        UserId = userId;
        OrderStatus = orderStatus;
        OrderDate = orderDate;
        PaymentMethod = paymentMethod;
        ShippingMethod = shippingmethod;
        VoucherId = voucherId;
        User = user;
        Voucher = voucher;
    }


}