// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics_Shop.DBModels;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Price { get; set; }

    public string Brand { get; set; }

    public string Category { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public string ImagePath { get; set; }

    public string ImageThumbnailPath { get; set; }

    public double AverageRating { get; set; }
}