// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Cosmetics_Shop.DBModels;

public partial class ShippingMethod
{
    public int Id { get; set; }

    public string MethodName { get; set; }

    public decimal ShippingCost { get; set; }
}